#!/bin/sh

find_params="\"$(pwd -P)\" -type f -name '*.[chyl]' ! -name '.*' ! -name '*.lex.[ch]' ! -name '*.tab.[ch]'"

rebuild_all()
{
	printf "rebuilding all tags..."
	rm -f tags
	eval find $find_params -exec ctags -aw {} +
	echo "done"
}

relevant_files()
{
	eval find $find_params -print | sort
}

old_files=/tmp/retags."$$"."$(awk 'BEGIN {srand();printf "%d\n", rand() * 10^10}')"
new_files=/tmp/retags."$$"."$(awk 'BEGIN {        printf "%d\n", rand() * 10^10}')"
cleanup()
{
	rm -f "$old_files" "$new_files"
	exit
}
trap cleanup TERM INT

# create tags from scratch
rebuild_all

# maintain them incrementally
relevant_files > "$new_files"
while true
do
	cp "$new_files" "$old_files"

	# entr will kill itself when files are changed/added
	entr -dps 'kill $PPID' < "$old_files" &
	wait # allow SIGINT through

	# remove entries for deleted files
	# (ctags claims it does this, but the macos one doesn't)
	relevant_files > "$new_files"
	printf "cleaning tags..."
	comm -23 "$old_files" "$new_files" | \
		xargs -I {} -L 1 ex -s -c ":g%{}%d" -c ":x" tags
	echo "done"
	
	# rebuild tags
	printf "updating tags..."
	xargs ctags -wu < "$new_files"
	echo "done"
done
